refactored renaming and added it as a separate command

diff --git a/screenlog b/screenlog
--- a/screenlog
+++ b/screenlog
@@ -1,7 +1,8 @@
 #!/bin/bash
 TARGET_DIR="$HOME/screenlog"
 PIDFILE="$TARGET_DIR/.$(basename "$0").pid"
-CURRENT_NOTE="$TARGET_DIR/current_note"
+CURRENT_NOTE_FILE="$TARGET_DIR/current_note"
+LAST_PREFIX_FILE="$TARGET_DIR/last_prefix"
 INTERVAL="$((60*5))" # take a screenshot every 5 minutes
 DATE_DIR_FORMAT='+%Y-%m-%d_%A'
 DATE_FILE_FORMAT='+%H-%M-%S'
@@ -13,10 +14,21 @@ Usage: $(basename "$0") <command> [args]
 Supported commands are:
     start [-d n]  - Start taking screenshots
     stop          - Stop taking screenshots
+    restart       - Restart screenlog
+    status        - Show running status
     take          - Take screenshot
+    last          - Display last screenshot
     list [date]   - List screenshots at date (default: today)
     time [date]   - List spent time by activity at date (default: today)
     show [string] - List spent time on matching activity
+    rename <note> - Changes last screenshot annotation
+    annotate [-d date] [-f from_time] [-t to_time] [-n] - Bulk rename
+                    -d defaults to today
+                    -f,-t are expressions in sed regex range. use
+                       something like -f 14: -t 15: to rename all
+                       screenshots starting from 14:00 but before 15:00
+                    -n do not rename, just display potential renames
+
 Requires scrot, zenity and rename (from util-linux) to work propperly.
 EOF
     exit 255
@@ -30,8 +42,12 @@ function running {
 }
 
 function set_note {
-    [ $# -eq 1 ] || { echo "Error: set_note takes exactly 1 argument"; exit 1; }
-    echo "$1" > "$CURRENT_NOTE"
+    echo "$*" > "$CURRENT_NOTE_FILE"
+}
+
+function set_last_prefix {
+    [ $# -eq 1 ] || { echo "Error: set_last_prefix requires 1 argument"; exit 1; }
+    echo "$1" > "$LAST_PREFIX_FILE"
 }
 
 function show_last {
@@ -40,19 +56,43 @@ function show_last {
     ls |tail -${N}|head -1|xargs -d "\n" sxiv
 }
 
+function make_filename { # (prefix, note)
+    PREFIX=$1
+    NOTE=$2
+    echo "$PREFIX ($NOTE).png"
+}
+
+function current_note {
+    cat "$CURRENT_NOTE_FILE"
+}
+
+function last_prefix {
+    cat "$LAST_PREFIX_FILE"
+}
+
+function rename_last {
+    [ -n "$1" ] || return # note should not be empty
+    NEW_NOTE=$1
+    NOTE="$(current_note)"
+    PREFIX="$(last_prefix)"
+    if [ "$NEW_NOTE" != "$NOTE" ]; then
+        set_note "$NEW_NOTE"
+        mv "$(make_filename "$PREFIX" "$NOTE")" "$(make_filename "$PREFIX" "$NEW_NOTE")"
+    fi
+}
+
 function take_screenshot {
     DAY_DIR="$TARGET_DIR/$(date "$DATE_DIR_FORMAT")"
     [ -d "$DAY_DIR" ] || mkdir -p "$DAY_DIR"
-    NOTE="$(cat "$CURRENT_NOTE")"
-    FILENAME="${DAY_DIR}/$(date "$DATE_FILE_FORMAT") ($NOTE).png"
+    NOTE="$(current_note)"
+    PREFIX="${DAY_DIR}/$(date "$DATE_FILE_FORMAT")"
+    FILENAME="$(make_filename "$PREFIX" "$NOTE")"
     import -window root "$FILENAME"
-    DURATION="$(date -u -d "@$(expr $(date +%s) - $(stat -c %Z "$CURRENT_NOTE"))" +%R)"
+    set_last_prefix "$PREFIX"
+    DURATION="$(date -u -d "@$(expr $(date +%s) - $(stat -c %Z "$CURRENT_NOTE_FILE"))" +%R)"
     MESSAGE="What you have been doing now, at $(date +%R) ?\nCurrent streak: $DURATION"
     NEW_NOTE="$(zenity --entry --entry-text="$NOTE" --text="$MESSAGE" || echo "$NOTE" )"
-    if [ "$NOTE" != "$NEW_NOTE" ]; then
-        rename "($NOTE)" "($NEW_NOTE)" "$FILENAME"
-        set_note "$NEW_NOTE"
-    fi
+    rename_last "$NEW_NOTE"
 }
 
 function take_screenshots {
@@ -185,6 +225,9 @@ case "$CMD" in
         ;;
     "list")
         list_at_date "$@"
+        ;;
+    "rename")
+        rename_last "$*"
         ;;
     "annotate")
         annotate "$@"
